openapi: 3.0.0
info:
  title: CommonGround API
  description: CommonGround API specification
  version: 0.0.1
servers:
  - url: https://localhost:8080
    description: Local server with WireGuard
paths:
  # Issue
  /api/issues:
    $ref: "./paths/issue.yaml#/Issues"
  /api/issue/{id}:
    $ref: "./paths/issue.yaml#/Issue"
  /api/issue/{id}/follow/me:
    $ref: "./paths/issue.yaml#/IssueFollow"
  /api/issue/{id}/facts:
    $ref: "./paths/issue.yaml#/IssueFacts"
  /api/issue/{id}/viewpoints:
    $ref: "./paths/viewpoint.yaml#/IssueViewPoints"

  # ViewPoint
  /api/viewpoints:
    $ref: "./paths/viewpoint.yaml#/ViewPoints"
  /api/viewpoint/{id}:
    $ref: "./paths/viewpoint.yaml#/ViewPoint"
  /api/viewpoint/{id}/reaction/me:
    $ref: "./paths/viewpoint.yaml#/ViewPointReaction"
  /api/viewpoint/{id}/facts:
    $ref: "./paths/viewpoint.yaml#/ViewPointFacts"
  /api/viewpoint/{id}/fact/{factId}:
    $ref: "./paths/viewpoint.yaml#/ViewPointFact"
  /api/viewpoint/{id}/replies:
    $ref: "./paths/reply.yaml#/ViewpointReplies"

  # Fact
  /api/facts:
    $ref: "./paths/fact.yaml#/Facts"
  /api/fact/{id}:
    $ref: "./paths/fact.yaml#/Fact"
  /api/fact/{id}/references:
    $ref: "./paths/fact.yaml#/FactReferences"
  /api/fact/{id}/reference/{referenceId}:
    $ref: "./paths/fact.yaml#/FactReference"

  # Reference
  /api/references:
    $ref: "./paths/reference.yaml#/References"

  # Timeline
  /api/issue/{id}/timeline:
    $ref: "./paths/timeline.yaml#/Timelines"
  /api/timeline/node/{id}:
    $ref: "./paths/timeline.yaml#/Timeline"

  # Reply
  /api/reply/{id}:
    $ref: "./paths/reply.yaml#/Reply"
  /api/reply/{id}/reaction/me:
    $ref: "./paths/reply.yaml#/ReplyReaction"

  # Website Title
  /api/website/check:
    $ref: "./paths/website.yaml#/WebsiteCheck"

  # UserSettings
  /api/user/setup:
    $ref: "./paths/user.yaml#/UserSetup"
  /api/user/settings:
    $ref: "./paths/user.yaml#/UserSettings"

  # Subscription
  /api/subscription/subscribe:
    $ref: "./paths/subscription.yaml#/Subscribe"
  /api/subscription/unsubscribe:
    $ref: "./paths/subscription.yaml#/Unsubscribe"

  # User
  /api/user/me:
    $ref: "./paths/user.yaml#/Me"
  /api/user/{username}:
    $ref: "./paths/user.yaml#/User"
  /api/users:
    $ref: "./paths/user.yaml#/Users"

  # Internal
  /api/internal/issues:
    $ref: "./paths/internal.yaml#/InternalIssues"
  /api/internal/issues/{issueId}:
    $ref: "./paths/internal.yaml#/InternalIssue"
  /api/internal/users/profile:
    $ref: "./paths/internal.yaml#/InternalProfiles"
  /api/internal/users/profile/{userId}:
    $ref: "./paths/internal.yaml#/InternalProfile"
  /api/internal/viewpoints/:
    $ref: "./paths/internal.yaml#/InternalViewpoints"
  /api/internal/viewpoints/{viewpointId}:
    $ref: "./paths/internal.yaml#/InternalViewpoint"
  /api/internal/embeddings:
    $ref: "./paths/internal.yaml#/InternalEmbeddings"
  /api/internal/similarities:
    $ref: "./paths/internal.yaml#/InternalUsersSimilarity"
  /api/internal/similarity/{userId}:
    $ref: "./paths/internal.yaml#/InternalUserSimilarity"

  #  ServiceAccount
  /api/internal/service-account/me:
    $ref: "./paths/service-account.yaml#/ServiceAccountMe"
  /api/internal/service-account/{serviceId}:
    $ref: "./paths/service-account.yaml#/ServiceAccount"
  /api/internal/service-accounts:
    $ref: "./paths/service-account.yaml#/ServiceAccounts"

  # Text-suggestion
  /api/text-suggestion:
    $ref: "./paths/text-suggestion.yaml#/TextSuggestion"
  /api/edited-text-suggestion:
    $ref: "./paths/text-suggestion.yaml#/EditedTextSuggestion"

components:
  schemas:
    Issue:
      $ref: "./schemas/issue.yaml#/Issue"
    UpdateIssue:
      $ref: "./schemas/issue.yaml#/UpdateIssue"
    IssueFacts:
      $ref: "./schemas/issue.yaml#/IssueFacts"
    IssueFollow:
      $ref: "./schemas/issue.yaml#/IssueFollow"
    UpdateIssueFollow:
      $ref: "./schemas/issue.yaml#/UpdateIssueFollow"
    ViewPoint:
      $ref: "./schemas/viewpoint.yaml#/ViewPoint"
    UpdateViewPoint:
      $ref: "./schemas/viewpoint.yaml#/UpdateViewPoint"
    ViewPointReaction:
      $ref: "./schemas/viewpoint.yaml#/ViewPointReaction"
    Fact:
      $ref: "./schemas/fact.yaml#/Fact"
    UpdateFact:
      $ref: "./schemas/fact.yaml#/UpdateFact"
    Reference:
      $ref: "./schemas/reference.yaml#/Reference"
    UpdateReference:
      $ref: "./schemas/reference.yaml#/UpdateReference"
    Reply:
      $ref: "./schemas/reply.yaml#/Reply"
    UpdateReply:
      $ref: "./schemas/reply.yaml#/UpdateReply"
    ReplyReaction:
      $ref: "./schemas/reply.yaml#/ReplyReaction"
    QuoteReply:
      $ref: "./schemas/reply.yaml#/QuoteReply"
    Subscribe:
      $ref: "./schemas/subscription.yaml#/Subscribe"
    Unsubscribe:
      $ref: "./schemas/subscription.yaml#/Unsubscribe"
    Pagination:
      $ref: "./schemas/page.yaml#/Page"
    InternalIssue:
      $ref: "./schemas/internal.yaml#/InternalIssue"
    InternalProfile:
      $ref: "./schemas/internal.yaml#/InternalProfile"
    InternalViewpoint:
      $ref: "./schemas/internal.yaml#/InternalViewpoint"
    InternalEmbedding:
      $ref: "./schemas/internal.yaml#/InternalEmbedding"
    CreateInternalEmbedding:
      $ref: "./schemas/internal.yaml#/CreateInternalEmbedding"
    UpdateInternalEmbedding:
      $ref: "./schemas/internal.yaml#/UpdateInternalEmbedding"
    InternalUserSimilarity:
      $ref: "./schemas/internal.yaml#/InternalUserSimilarity"
    TextSuggestion:
      $ref: "./schemas/text-suggestion.yaml#/TextSuggestion"
    TextSuggestionResponse:
      $ref: "./schemas/text-suggestion.yaml#/TextSuggestionResponse"
    EditedTextSuggestion:
      $ref: "./schemas/text-suggestion.yaml#/EditedTextSuggestion"
    EditedTextSuggestionRequest:
      $ref: "./schemas/text-suggestion.yaml#/EditedTextSuggestionRequest"
    EditedTextSuggestionResponse:
      $ref: "./schemas/text-suggestion.yaml#/EditedTextSuggestionResponse"
