openapi: 3.0.0
info:
  title: Sample API
  description: A simple API example
  version: 1.0.0
servers:
  - url: https://your-api-server.com
paths:
  # Fact
  /facts:
    get:
      summary: List facts
      description: This endpoint returns all facts
      operationId: getFactsList
      tags:
        - Fact
      parameters:
        - $ref: "./parameters/sort.yaml"
        - $ref: "./parameters/page.yaml"
        - $ref: "./parameters/size.yaml"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  embedded:
                    type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: "./schemas/response/fact.yaml"
                  page:
                    $ref: "./schemas/response/page.yaml"

    post:
      summary: Create a new fact
      description: This endpoint is used to create a new fact for user
      operationId: CreateFact
      tags:
        - Fact
      parameters:
        - name: fact
          in: body
          description: New created fact
          required: true
          schema:
            $ref: "./schemas/request/fact.yaml"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "./schemas/response/fact.yaml"

  /facts/{id}:
    get:
      summary: Get specific fact information
      description: This endpoint returns specific fact information by fact id
      operationId: GetFact
      tags:
        - Fact
      parameters:
        - $ref: "./parameters/requestId.yaml"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "./schemas/response/fact.yaml"
        '404':
          $ref: "./definitions/dataNotFound.yaml"

    put:
      summary: Update properties for a selected fact
      description: This endpoint is used to update properties of specific fact by fact id
      operationId: UpdateFact
      tags:
        - Fact
      parameters:
        - $ref: "./parameters/requestId.yaml"
        - name: fact
          in: body
          description: Updates of fact
          required: true
          schema:
            $ref: "./schemas/request/fact.yaml"
      responses:
        '200':
          $ref: "./definitions/requestSuccess.yaml"

    delete:
      summary: Delete selected fact
      description: This endpoint is used to delete specific fact by fact id
      operationId: DeletedFact
      tags:
        - Fact
      parameters:
        - $ref: "./parameters/requestId.yaml"
      responses:

  /facts/{id}/references:
    get:
      summary: List references of specific fact
      description: This endpoint returns references of specific fact by fact id
      operationId: GetFactReferences
      tags:
        - Fact
      parameters:
        - $ref: "./parameters/requestId.yaml"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./schemas/response/reference.yaml"
    post:
      summary: Add references to specific fact
      description: This endpoint is used to add new reference to specific fact by fact id
      operationId: AddReferences
      tags:
        - Fact
      parameters:
        - $ref: "./parameters/requestId.yaml"
        - name: reference
          in: body
          description: New created fact
          required: true
          schema:
            type: array
            items:
              $ref: "./schemas/request/reference.yaml"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./schemas/response/reference.yaml"
    delete:
      summary: Delete selected reference
      description: This endpoint is used to delete specific reference by reference id
      operationId: DeletedReference
      tags:
        - Fact
      parameters:
        - $ref: "./parameters/requestId.yaml"
      responses:
        '204':
          $ref: "./definitions/processSuccess.yaml"
