openapi: 3.0.0
info:
  title: Sample API
  description: A simple API example
  version: 1.0.0
servers:
  - url: https://your-api-server.com
paths:
  # Fact
  /facts:
    $ref: "./paths/fact.yaml#/Facts"
  /facts/{id}:
    $ref: "./paths/fact.yaml#/Fact"
  /facts/{id}/references:
    $ref: "./paths/fact.yaml#/FactReferences"
