openapi: 3.0.0
info:
  title: CommonGround API
  description: A simple API example
  version: 1.0.0
servers:
  - url: https://your-api-server.com
paths:
  # ViewPoint
  /api/viewpoints:
    $ref: "./paths/viewpoint.yaml#/ViewPoints"
  /api/viewpoint/{id}:
    $ref: "./paths/viewpoint.yaml#/ViewPoint"
  /api/viewpoint/{id}/likes:
    $ref: "./paths/viewpoint.yaml#/ViewPointLikes"
  /api/viewpoint/{id}/like/me:
    $ref: "./paths/viewpoint.yaml#/ViewPointLikeMe"
  /api/viewpoint/{id}/reasonables:
    $ref: "./paths/viewpoint.yaml#/ViewPointReasonables"
  /api/viewpoint/{id}/reasonable/me:
    $ref: "./paths/viewpoint.yaml#/ViewPointReasonableMe"
  /api/viewpoint/{id}/dislikes:
    $ref: "./paths/viewpoint.yaml#/ViewPointDislikes"
  /api/viewpoint/{id}/dislike/me:
    $ref: "./paths/viewpoint.yaml#/ViewPointDislikeMe"
  /api/viewpoint/{id}/facts:
    $ref: "./paths/viewpoint.yaml#/ViewPointFacts"
  /api/viewpoint/{id}/fact/{factId}:
    $ref: "./paths/viewpoint.yaml#/ViewPointFact"
  # Fact
  /api/facts:
    $ref: "./paths/fact.yaml#/Facts"
  /api/fact/{id}:
    $ref: "./paths/fact.yaml#/Fact"
  /api/fact/{id}/references:
    $ref: "./paths/fact.yaml#/FactReferences"
